### ISSUE TITLE
设计模式没有内容

### ISSUE THREAD

**Issue by wayss000** [xucongli1989/MyMindMap#1]
你好，关于设计模式的思维导图：https://github.com/xucongli1989/MyMindMap/tree/master/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F ，
没有内容，请问是否是bug？

**Comment by xucongli1989** [comment]
有内容的，请检查打开方式是否正确。

**Comment by wayss000** [comment]
OK。我之前点了右键另存为了。点击页面的Download就可以。
谢谢你。
